config/routes.rb
Rails.application.routes.draw do
  root to: 'public#main'
  get '/dashboard' => 'dashboard#index', as: :dashboard
  get '/profile/:id' => 'dashboard#profile', as: :profile
  resources :properties
  devise_for :accounts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  mount_uploader :image, ProfilePictureUploader
  has_many :properties

  def full_name
      "#{first_name} #{last_name}"
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/property.rb
class Property < ApplicationRecord
    mount_uploader :photo, PhotoUploader
    belongs_to  :account

    scope :latest, -> { order created_at: :desc }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :url, :image, :image_cache,:company])
        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :url])
    end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  before_action :set_sidebar

  def index
  end

  def profile
    @account = Account.find(params[:id])
  end

  private

  def set_sidebar
    @show_sidebar = true
  end

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_account!, only: [:new, :create, :destroy]
  before_action :set_sidebar, except: [:show]

  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
    @agent = @property.account
    @agent_properties = Property.where(account_id: @agent.id).where.not(id: @property.id)
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)
    @property.account_id = current_account.id

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    def set_sidebar
      @show_sidebar = true
    end
    # Only allow a list of trusted parameters through.
    def property_params
      params.require(:property).permit(:name, :address, :price, :rooms, :bathrooms, :parking_spaces,:details, :photo, :photo_cache, :for_sal,:available_date)
    end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def main

    if account_signed_in?
      redirect_to dashboard_path, flash: { success: "Successfully signed in. Welcome to Property Finder!" } and return
    end

    @properties = Property.latest
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def profile_picture account, width = 100
      thumb = account.image.present? ? account.image.thumb.url : "placeholder.png"
      image_tag thumb, width: width, class: "profile-pic img-circle"
  end

  def flash_notifications
    flash_messages = []

    flash.each do |type, message|
      type = 'success' if type == 'notice'
      type = 'error' if type == 'alert' || type == 'danger'
      text = "toastr['#{type}']('#{message}');"
      flash_messages << text.html_safe unless message.blank?
    end
    "<script>$(function(){ #{flash_messages.join("\n")} });</script>".html_safe if flash_messages.any?
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper

  def property_thumbnail property
    img = property.photo.present? ? property.photo.thumb.url : "placeholder.png"
    image_tag img, class:"property-thumb"
  end

  def property_thumbnail_url property
    property.photo.present? ? property.photo.thumb.url : "placeholder.png"
  end

  def property_photo_url property
    img = property.photo.present? ? property.photo.url : asset_url("placeholder.png")
  end
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/dashboard/index.html.erb
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="h2">Dashboard</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
          <div class="btn-group mr-2">
            <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
            <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
          </div>
          <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-calendar"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect><line x1="16" y1="2" x2="16" y2="6"></line><line x1="8" y1="2" x2="8" y2="6"></line><line x1="3" y1="10" x2="21" y2="10"></line></svg>
            This week
          </button>
        </div>
      </div>

      <!-- #canvas class="my-4 w-100 chartjs-render-monitor" id="myChart" width="1984" height="836" style="display: block; height: 418px; width: 992px;"></canvas> -->

      <!-- <h2>Section title</h2> -->
      <div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th>#</th>
              <th>Header</th>
              <th>Header</th>
              <th>Header</th>
              <th>Header</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>1,001</td>
              <td>Lorem</td>
              <td>ipsum</td>
              <td>dolor</td>
              <td>sit</td>
            </tr>
            <tr>
              <td>1,002</td>
              <td>amet</td>
              <td>consectetur</td>
              <td>adipiscing</td>
              <td>elit</td>
            </tr>
            <tr>
              <td>1,003</td>
              <td>Integer</td>
              <td>nec</td>
              <td>odio</td>
              <td>Praesent</td>
            </tr>
            <tr>
              <td>1,003</td>
              <td>libero</td>
              <td>Sed</td>
              <td>cursus</td>
              <td>ante</td>
            </tr>
          </tbody>
        </table>
      </div>
    </main>
  </div>
</div>

app/views/dashboard/profile.html.erb
<p><%= @account.full_name%></p>

app/views/dashboard/properties.html.erb
<h1>Dashboard#properties</h1>
<p>Find me in app/views/dashboard/properties.html.erb</p>

app/views/dashboard/reports.html.erb
<h1>Dashboard#reports</h1>
<p>Find me in app/views/dashboard/reports.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="container">
  <p>© Property Finder 2017-2020</p>
</footer>

app/views/layouts/_validation.html.erb
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PropertyFinder</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="apple-touch-icon" sizes="180x180" href="<%= asset_url "favicon_io/apple-touch-icon.png" %>">
    <link rel="icon" type="image/png" sizes="32x32" href="<%= asset_url "favicon_io/favicon-32x32.png" %>">
    <link rel="icon" type="image/png" sizes="16x16" href="<%= asset_url "favicon_io/favicon-16x16.png" %>">


  </head>
 <body id="<%= controller.controller_name %>" class="<%= controller.action_name %> <%= "show_sidebar" if @show_sidebar.present? %>">
 <% if @show_sidebar.nil? %>
  <header>
    <%= render "layouts/nav/public"%>
  </header>
    <%= yield %>

  <% else %>
    <%= render "layouts/nav/dashboard"%>

    <div class="container-fluid">
      <div class="row">
      <%= render 'layouts/nav/sidebar' %>
      <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4 mt-4">
        <%= yield %>
        </main>
      </div>
    </div>
  <% end %>


  <%#= render "layouts/footer"%>

  <div id="notifications"><%= flash_notifications %></div>

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/nav/_dashboard.html.erb
<nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Property Finder</a>
  <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <%= link_to "Log out", destroy_account_session_path, method: :delete, class:"nav-link"%>
    </li>
  </ul>
</nav>

app/views/layouts/nav/_public.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" >
  <%= link_to "Property Finder", root_path,  class:"nav-link" %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
      <% if account_signed_in? %>
      <%= link_to "Dashboard", dashboard_path, class:"nav-link"%>
      <% else %>
      <% end %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/">Latest</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>

    <% if account_signed_in?%>
    <li class="nav-item">
      <%= link_to "Log out", destroy_account_session_path, method: :delete, class:"nav-link"%>
    <% else %>
        <%= link_to "Log In", new_account_session_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
            <%= link_to "Sign Up", new_account_registration_path, class:"nav-link" %>
      </li>

    <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/nav/_sidebar.html.erb
    <nav class="col-md-2 d-none d-md-block bg-light sidebar">
      <div class="sidebar-sticky">
        <ul class="nav flex-column">
          <li class="nav-item">
            <%= link_to dashboard_path, class:"nav-link" do %>
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
              Dashboard <span class="sr-only">(current)</span>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to properties_path, class:"nav-link" do %>
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file"><path d="M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"></path><polyline points="13 2 13 9 20 9"></polyline></svg>
              Properties
            <% end %>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-shopping-cart"><circle cx="9" cy="21" r="1"></circle><circle cx="20" cy="21" r="1"></circle><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"></path></svg>
              Contacts
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-bar-chart-2"><line x1="18" y1="20" x2="18" y2="10"></line><line x1="12" y1="20" x2="12" y2="4"></line><line x1="6" y1="20" x2="6" y2="14"></line></svg>
              Reports
            </a>
          </li>
          </ul>
        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Settings</span>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
              <%= link_to profile_path(current_account), class: "nav-link" do %>
                  My profile
              <% end %>
            </li>
          <li class="nav-item">
              <%= link_to edit_account_registration_path, class: "nav-link" do %>
                  Account Settings
              <% end %>
            </li>
        </ul>
      </div>
    </nav>

app/views/properties/_agent_details.html.erb
<div class="text-center border pt-5 pb-5 ml-5">
  <div class="mb-2">
    <%= profile_picture @agent %>
  </div>

  <h3 class="h4"><%= @agent.full_name %></h3>
  <p><%= @agent.company %></p>

  <button class="btn btn-info text-uppercase">Call</button>
  <button class="btn btn-success text-uppercase">Email</button>

</div>

app/views/properties/_form.html.erb
<%= form_with(model: property, local: true) do |form| %>

  <%= render "layouts/validation", item: @property %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_field :address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :price, "Total Price (for sale) / Monthly Price (rental)" %>
    <%= form.number_field :price, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :rooms %>
    <%= form.number_field :rooms, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :bathrooms %>
    <%= form.number_field :bathrooms, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :parking_spaces %>
    <%= form.number_field :parking_spaces, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :for_sale %>
    <%= form.select :for_sale, options_for_select({ "Yes" => true, "No" => false }, @property.for_sale), class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :available_date %>
    <%= form.date_field :available_date, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :details %>
    <%= form.text_area :details, class: "form-control" %>
  </div>


    <div class="form-group">
    <%= form.label :photo %>
    <%= form.file_field :photo, class: "form-control" %>
    <%= form.hidden_field :photo_cache %>

    <% if @property.photo.present? %>
      <%= image_tag property.photo.url, class:"mt-4" %>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.submit "Save Property", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/properties/_list.html.erb
<% properties.each do |property| %>
  <div class="col-4">
    <div class="property border">
    <div class="property-thumb" style="background-image: url(<%= property_thumbnail_url(property) %>)">
      <%= link_to "", property_path(property) %>
    </div>

    <div class="property-summary p-3">

      <h3 class="h5"><%= link_to property.name, property_path(property), class:"text-dark" %></h3>

      <span class="mr-2"><i class="fa fa-bed text-muted" ></i> <%= property.rooms %></span>
      <span class="mr-2"><i class="fa fa-bath text-muted"></i> <%= property.bathrooms %></span>
      <span><i class="fa fa-car text-muted"></i>  <%= property.parking_spaces %></span>

      <p class="mt-2"><%= property.address %></p>
    </div>
  </div>
</div>
<% end %>

app/views/properties/edit.html.erb
<h1 class="h3">Editing Property</h1>

<%= render 'form', property: @property %>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="h3">Properties</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Price</th>
      <th>Rooms</th>
      <th>Bathrooms</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.name %></td>
        <td><%= property.address %></td>
        <td><%= property.price %></td>
        <td><%= property.rooms %></td>
        <td><%= property.bathrooms %></td>
        <td><%= link_to 'Show', property %></td>
        <td><%= link_to 'Edit', edit_property_path(property) %></td>
        <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property', new_property_path, class:"btn btn-primary" %>

app/views/properties/new.html.erb
<h1 class="h3">New Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<div class="property-main-photo" style="background-image:url('<%= property_photo_url @property %>')">
    <div class="photo-overlay">

    </div>
</div>
<div class="container">
<div class="row">
  <div class="col-sm-8">
  <div class="row">
    <div class="col-lg-4">
          <p class="mb-0 h4"><%= @property.for_sale? ? "For Sale" : "For Rent"%></p>
          <p class="mb-2 mt-2 h7"><%= @property.address%></p>
          <p class="h2 mb-3">
          <% if @property.for_sale? %>
              <%= @property.price > 0 ? number_to_currency(@property.price, precision: 0) : "Offers Accepted" %>
          <% else %>
              <%= @property.price > 0 ? number_to_currency(@property.price, precision: 0) : "Open for enquiries" %>
          <% end %>
          </p>
      </div>
      <div class="col-lg-7 ml-5 text-center">
        <div class="row mr-lg-3 mt-sm-3 bg-light p-3">
              <div class="col-4">
                <i class="fa fa-bed text-muted m-0" ></i> <br>
               <small><%= @property.rooms %> Rooms</small>

              </div>
              <div class="col-4">
              <i class="fa fa-bath text-muted m-0" ></i><br>
                <small><%= @property.bathrooms %> Bathrooms</small>
              </div>
              <div class="col-4">
                <i class="fa fa-car text-muted m-0" ></i><br>
                <small><%= @property.parking_spaces %> Parking </small>
              </div>
            </div>
          </div>
      </div>

  <div class="row border-top border-bottom mt-4 mb-5 pt-4 pb-4">
    <div class="col-6">
    <% if @property.for_sale? %>
        <strong><%= link_to "Est. Monthly Repayments of #{number_to_currency((@property.price - (@property.price * 0.1)) / 360, precision: 0)}*", "#", class:"text-success"%></strong>
    <% else %>
      <strong>Available from <%= @property.available_date.strftime("%a") %>, <%= @property.available_date.day.ordinalize %> <%= @property.available_date.strftime("%b") %></strong>
    <% end %>
    </div>
    <div class="col-sm-6 text-right">
      <strong><%= link_to "Can I afford this property?", "#", class:"text-success" %></strong>
    </div>
</div>
<div class="row">
    <div class="col-md">
        <p class="h3"><%= @property.name %></p>
        <p class="h5">Property Description </p>

        <div id="prop-details" class="mt-5">
        <%= simple_format @property.details %>
        </div>

        <button class="btn btn-outline-info mt-3" id="toggleDetails">Show more</button>

        <p class="mt-5">* This rate is based on a 30 year mortgage, after paying an initial 10% down payment. Shorter term mortages would require a higher monthly repayment.</p>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <%= render "properties/agent_details" %>
  <iframe
  class="ml-lg-4 mt-3"
  width="320"
  height="240"
  frameborder="0" style="border:0"
  src="https://www.google.com/maps/embed/v1/place?key=&q=<%= @property.address.to_param%>" allowfullscreen>
</iframe>

  </div>
</div>
</div>

  <section class="mt-5 mb-5">
    <div class="container">
      <div class="row">
       <div class="col-12">
          <p class="h3 mb-4">Other properties by this agent</p>
       </div>
       <%= render "properties/list", properties: @agent_properties %>
      </div>
    </div>
  </section>